spring.application.name=checker-service
server.port=8082

# DB
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/deadlink}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:deadlink}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:deadlink}
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.schemas=checker
spring.flyway.table=flyway_schema_history_checker
spring.flyway.default-schema=checker


# Kafka
#spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=checker-service-group
spring.kafka.consumer.auto-offset-reset=earliest