spring.application.name=crawler-service
server.port=8081

# DB
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/deadlink}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:deadlink}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:deadlink}
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.schemas=crawler
spring.flyway.table=flyway_schema_history_crawler
spring.flyway.default-schema=crawler

# Kafka
#spring.kafka.bootstrap-servers=localhost:9092

# Disable Kafka auto-startup for now
spring.kafka.consumer.auto-offset-reset=earliest
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

spring.task.scheduling.pool.size=5